package dao;
// Generated Jun 16, 2018 2:52:34 PM by Hibernate Tools 4.3.1



/**
 * Caixa generated by hbm2java
 */
public class Caixa  implements java.io.Serializable {


     private CaixaId id;
     private Armazem armazem;
     private Produto produto;
     private short quantidade;

    public Caixa() {
    }

    public Caixa(CaixaId id, Armazem armazem, Produto produto, short quantidade) {
       this.id = id;
       this.armazem = armazem;
       this.produto = produto;
       this.quantidade = quantidade;
    }
   
    public CaixaId getId() {
        return this.id;
    }
    
    public void setId(CaixaId id) {
        this.id = id;
    }
    public Armazem getArmazem() {
        return this.armazem;
    }
    
    public void setArmazem(Armazem armazem) {
        this.armazem = armazem;
    }
    public Produto getProduto() {
        return this.produto;
    }
    
    public void setProduto(Produto produto) {
        this.produto = produto;
    }
    public short getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(short quantidade) {
        this.quantidade = quantidade;
    }




}


