package dao;
// Generated Jun 16, 2018 2:52:34 PM by Hibernate Tools 4.3.1



/**
 * CaixaId generated by hbm2java
 */
public class CaixaId  implements java.io.Serializable {


     private int idarmazem;
     private int idcaixa;

    public CaixaId() {
    }

    public CaixaId(int idarmazem, int idcaixa) {
       this.idarmazem = idarmazem;
       this.idcaixa = idcaixa;
    }
   
    public int getIdarmazem() {
        return this.idarmazem;
    }
    
    public void setIdarmazem(int idarmazem) {
        this.idarmazem = idarmazem;
    }
    public int getIdcaixa() {
        return this.idcaixa;
    }
    
    public void setIdcaixa(int idcaixa) {
        this.idcaixa = idcaixa;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CaixaId) ) return false;
		 CaixaId castOther = ( CaixaId ) other; 
         
		 return (this.getIdarmazem()==castOther.getIdarmazem())
 && (this.getIdcaixa()==castOther.getIdcaixa());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdarmazem();
         result = 37 * result + this.getIdcaixa();
         return result;
   }   


}


