package dao;
// Generated Jun 16, 2018 2:52:34 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Localidade generated by hbm2java
 */
public class Localidade  implements java.io.Serializable {


     private int idlocalidade;
     private String nome;
     private Set<Loja> lojas = new HashSet<Loja>(0);
     private Set<Armazem> armazems = new HashSet<Armazem>(0);

    public Localidade() {
    }

	
    public Localidade(int idlocalidade, String nome) {
        this.idlocalidade = idlocalidade;
        this.nome = nome;
    }
    public Localidade(int idlocalidade, String nome, Set<Loja> lojas, Set<Armazem> armazems) {
       this.idlocalidade = idlocalidade;
       this.nome = nome;
       this.lojas = lojas;
       this.armazems = armazems;
    }
   
    public int getIdlocalidade() {
        return this.idlocalidade;
    }
    
    public void setIdlocalidade(int idlocalidade) {
        this.idlocalidade = idlocalidade;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set<Loja> getLojas() {
        return this.lojas;
    }
    
    public void setLojas(Set<Loja> lojas) {
        this.lojas = lojas;
    }
    public Set<Armazem> getArmazems() {
        return this.armazems;
    }
    
    public void setArmazems(Set<Armazem> armazems) {
        this.armazems = armazems;
    }




}


