package dao;
// Generated Jun 16, 2018 2:52:34 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Marca generated by hbm2java
 */
public class Marca  implements java.io.Serializable {


     private int idmarca;
     private String nome;
     private Set<Produto> produtos = new HashSet<Produto>(0);

    public Marca() {
    }

	
    public Marca(int idmarca, String nome) {
        this.idmarca = idmarca;
        this.nome = nome;
    }
    public Marca(int idmarca, String nome, Set<Produto> produtos) {
       this.idmarca = idmarca;
       this.nome = nome;
       this.produtos = produtos;
    }
   
    public int getIdmarca() {
        return this.idmarca;
    }
    
    public void setIdmarca(int idmarca) {
        this.idmarca = idmarca;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set<Produto> getProdutos() {
        return this.produtos;
    }
    
    public void setProdutos(Set<Produto> produtos) {
        this.produtos = produtos;
    }




}


