package dao;
// Generated Jun 16, 2018 2:52:34 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tamanho generated by hbm2java
 */
public class Tamanho  implements java.io.Serializable {


     private int idtamanho;
     private String descricao;
     private Set<Produto> produtos = new HashSet<Produto>(0);

    public Tamanho() {
    }

	
    public Tamanho(int idtamanho, String descricao) {
        this.idtamanho = idtamanho;
        this.descricao = descricao;
    }
    public Tamanho(int idtamanho, String descricao, Set<Produto> produtos) {
       this.idtamanho = idtamanho;
       this.descricao = descricao;
       this.produtos = produtos;
    }
   
    public int getIdtamanho() {
        return this.idtamanho;
    }
    
    public void setIdtamanho(int idtamanho) {
        this.idtamanho = idtamanho;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Set<Produto> getProdutos() {
        return this.produtos;
    }
    
    public void setProdutos(Set<Produto> produtos) {
        this.produtos = produtos;
    }




}


