package dao;
// Generated Jun 16, 2018 2:52:34 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tipoproduto generated by hbm2java
 */
public class Tipoproduto  implements java.io.Serializable {


     private int idtipoproduto;
     private String nome;
     private Set<Produto> produtos = new HashSet<Produto>(0);

    public Tipoproduto() {
    }

	
    public Tipoproduto(int idtipoproduto, String nome) {
        this.idtipoproduto = idtipoproduto;
        this.nome = nome;
    }
    public Tipoproduto(int idtipoproduto, String nome, Set<Produto> produtos) {
       this.idtipoproduto = idtipoproduto;
       this.nome = nome;
       this.produtos = produtos;
    }
   
    public int getIdtipoproduto() {
        return this.idtipoproduto;
    }
    
    public void setIdtipoproduto(int idtipoproduto) {
        this.idtipoproduto = idtipoproduto;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set<Produto> getProdutos() {
        return this.produtos;
    }
    
    public void setProdutos(Set<Produto> produtos) {
        this.produtos = produtos;
    }




}


