package dao;
// Generated Jun 16, 2018 2:52:34 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Venda generated by hbm2java
 */
public class Venda  implements java.io.Serializable {


     private int idvenda;
     private Funcionario funcionario;
     private Loja loja;
     private Tipopagamento tipopagamento;
     private Date datavenda;
     private double valortotal;
     private double valorganho;
     private boolean estado;
     private Set<Produtovenda> produtovendas = new HashSet<Produtovenda>(0);

    public Venda() {
    }

	
    public Venda(int idvenda, Funcionario funcionario, Loja loja, Tipopagamento tipopagamento, Date datavenda, double valortotal, double valorganho, boolean estado) {
        this.idvenda = idvenda;
        this.funcionario = funcionario;
        this.loja = loja;
        this.tipopagamento = tipopagamento;
        this.datavenda = datavenda;
        this.valortotal = valortotal;
        this.valorganho = valorganho;
        this.estado = estado;
    }
    public Venda(int idvenda, Funcionario funcionario, Loja loja, Tipopagamento tipopagamento, Date datavenda, double valortotal, double valorganho, boolean estado, Set<Produtovenda> produtovendas) {
       this.idvenda = idvenda;
       this.funcionario = funcionario;
       this.loja = loja;
       this.tipopagamento = tipopagamento;
       this.datavenda = datavenda;
       this.valortotal = valortotal;
       this.valorganho = valorganho;
       this.estado = estado;
       this.produtovendas = produtovendas;
    }
   
    public int getIdvenda() {
        return this.idvenda;
    }
    
    public void setIdvenda(int idvenda) {
        this.idvenda = idvenda;
    }
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public Loja getLoja() {
        return this.loja;
    }
    
    public void setLoja(Loja loja) {
        this.loja = loja;
    }
    public Tipopagamento getTipopagamento() {
        return this.tipopagamento;
    }
    
    public void setTipopagamento(Tipopagamento tipopagamento) {
        this.tipopagamento = tipopagamento;
    }
    public Date getDatavenda() {
        return this.datavenda;
    }
    
    public void setDatavenda(Date datavenda) {
        this.datavenda = datavenda;
    }
    public double getValortotal() {
        return this.valortotal;
    }
    
    public void setValortotal(double valortotal) {
        this.valortotal = valortotal;
    }
    public double getValorganho() {
        return this.valorganho;
    }
    
    public void setValorganho(double valorganho) {
        this.valorganho = valorganho;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public Set<Produtovenda> getProdutovendas() {
        return this.produtovendas;
    }
    
    public void setProdutovendas(Set<Produtovenda> produtovendas) {
        this.produtovendas = produtovendas;
    }




}


